export const employeeOrdersMock = [
  {
    id: 1042,
    shipmentNumber: 'PHX-1042',
    status: 'available',
    price: 35,
    time: '10:30 - 11:00',
    parcelType: 'طرد طعام',
    parcelDescription: 'وجبات عائلية ومشروبات باردة',
    specialNotes: 'التواصل قبل الوصول بخمس دقائق',
    pickupAddress: 'رفيديا - مطعم البيك',
    senderName: 'مطعم البيك',
    senderPhone: '0599123456',
    deliveryAddress: 'المخفية - شارع الحسبة',
    receiverName: 'محمد خالد',
    receiverPhone: '0599001122',
    proofImage: null,
  },
  {
    id: 1068,
    shipmentNumber: 'PHX-1068',
    status: 'available',
    price: 42,
    time: '11:15 - 12:00',
    parcelType: 'طرد متجر',
    parcelDescription: 'ملابس وإكسسوارات خفيفة',
    specialNotes: 'يرجى الحفاظ على الكيس بشكل مستقيم',
    pickupAddress: 'شارع الجامعة - متجر الأناقة',
    senderName: 'متجر الأناقة',
    senderPhone: '0567456123',
    deliveryAddress: 'حي المعاجين - عمارة الندى',
    receiverName: 'لينا سمير',
    receiverPhone: '0598112233',
    proofImage: null,
  },
  {
    id: 1095,
    shipmentNumber: 'PHX-1095',
    status: 'in_progress',
    price: 28,
    time: '12:30 - 01:10',
    parcelType: 'توصيل أدوية',
    parcelDescription: 'مستحضرات طبية وأدوية موصوفة',
    specialNotes: 'التسليم لشخص بالغ فقط',
    pickupAddress: 'دوار نابلس - صيدلية الحياة',
    senderName: 'صيدلية الحياة',
    senderPhone: '0598774411',
    deliveryAddress: 'البلدة القديمة - قرب البنك العربي',
    receiverName: 'أحمد ناصر',
    receiverPhone: '0599445566',
    proofImage: null,
  },
  {
    id: 1111,
    shipmentNumber: 'PHX-1111',
    status: 'in_progress',
    price: 51,
    time: '02:00 - 02:40',
    parcelType: 'مستندات رسمية',
    parcelDescription: 'ملف أوراق مختوم يحتاج عناية',
    specialNotes: 'يمنع طي المستندات أثناء النقل',
    pickupAddress: 'المنطقة الصناعية - مخزن فينوكس',
    senderName: 'مخزن فينوكس',
    senderPhone: '0599332211',
    deliveryAddress: 'شارع القدس - برج الياسمين',
    receiverName: 'سارة يوسف',
    receiverPhone: '0567008899',
    proofImage: null,
  },
  {
    id: 1008,
    shipmentNumber: 'PHX-1008',
    status: 'completed',
    price: 39,
    time: '09:00 - 09:40',
    parcelType: 'طلب منزلي',
    parcelDescription: 'مواد تموينية متنوعة',
    specialNotes: 'تم التسليم بنجاح',
    pickupAddress: 'شارع التعاون - متجر الريف',
    senderName: 'متجر الريف',
    senderPhone: '0569987123',
    deliveryAddress: 'المساكن الشعبية - بناية 8',
    receiverName: 'رامي جودة',
    receiverPhone: '0599223344',
    proofImage: 'delivery-proof-1008.jpg',
  },
  {
    id: 1019,
    shipmentNumber: 'PHX-1019',
    status: 'completed',
    price: 47,
    time: '03:00 - 03:45',
    parcelType: 'هدية',
    parcelDescription: 'باقة ورد مع بطاقة إهداء',
    specialNotes: 'التسليم عند الباب الخارجي',
    pickupAddress: 'شارع عمان - محل الورود',
    senderName: 'محل الورود',
    senderPhone: '0599002217',
    deliveryAddress: 'الجبل الشمالي - فيلا 12',
    receiverName: 'هديل جمال',
    receiverPhone: '0599442217',
    proofImage: 'delivery-proof-1019.jpg',
  },
];
