// TODO: Replace dummy reports service with real API calls after admin reports endpoints are approved.
//
// Future backend mapping guide:
// - orders: orderNumber, merchant/customer references, paymentMethod, amount, createdAt.
// - shipments: status, delegate assignment, city, area, updatedAt, returnedAt, returnReason.
// - customers: customerName and phone.
// - employees: delegateName.
// - wallet_transactions: collectedAmount, phoenixCommission, merchantDue.
//
// Expected future signatures:
// - getAdminReports() => GET /api/admin/reports
// - getReturnedOrders() => GET /api/admin/reports/returned

const REPORTS_DATA = [
  {
    id: 1,
    orderNumber: "PX-1045",
    merchantName: "متجر الأناقة",
    customerName: "ليان شحادة",
    phone: "0599123456",
    delegateName: "أحمد محمد",
    status: "delivered",
    paymentMethod: "cod",
    amount: 260,
    collectedAmount: 260,
    phoenixCommission: 32,
    merchantDue: 228,
    city: "رام الله",
    area: "حي الطيرة",
    createdAt: "2026-04-19T09:15:00",
    updatedAt: "2026-04-20T14:20:00",
  },
  {
    id: 2,
    orderNumber: "PX-1046",
    merchantName: "متجر الإلكترونيات",
    customerName: "عمر دراغمة",
    phone: "0599554411",
    delegateName: "محمد علي",
    status: "in_delivery",
    paymentMethod: "cod",
    amount: 480,
    collectedAmount: 0,
    phoenixCommission: 0,
    merchantDue: 0,
    city: "نابلس",
    area: "حي رفيديا",
    createdAt: "2026-04-21T11:40:00",
    updatedAt: "2026-04-24T10:10:00",
  },
  {
    id: 3,
    orderNumber: "PX-1047",
    merchantName: "متجر الكتب",
    customerName: "هبة جرار",
    phone: "0599442200",
    delegateName: "خالد أحمد",
    status: "returned",
    paymentMethod: "cod",
    amount: 135,
    collectedAmount: 0,
    phoenixCommission: 0,
    merchantDue: 0,
    city: "جنين",
    area: "حي الجواشين",
    createdAt: "2026-04-18T08:25:00",
    updatedAt: "2026-04-22T16:45:00",
  },
  {
    id: 4,
    orderNumber: "PX-1048",
    merchantName: "متجر الأزياء",
    customerName: "سارة قنديل",
    phone: "0599336677",
    delegateName: "عبدالله سالم",
    status: "delivered",
    paymentMethod: "wallet",
    amount: 310,
    collectedAmount: 310,
    phoenixCommission: 38,
    merchantDue: 272,
    city: "بيت لحم",
    area: "البلدة القديمة",
    createdAt: "2026-04-20T13:05:00",
    updatedAt: "2026-04-21T18:12:00",
  },
  {
    id: 5,
    orderNumber: "PX-1049",
    merchantName: "متجر العطور",
    customerName: "يزن نخلة",
    phone: "0599776655",
    delegateName: "أحمد محمد",
    status: "pending",
    paymentMethod: "bank_transfer",
    amount: 190,
    collectedAmount: 0,
    phoenixCommission: 0,
    merchantDue: 0,
    city: "الخليل",
    area: "وسط البلد",
    createdAt: "2026-04-24T09:50:00",
    updatedAt: "2026-04-24T09:50:00",
  },
  {
    id: 6,
    orderNumber: "PX-1050",
    merchantName: "متجر المنزل",
    customerName: "رنا أبو لبدة",
    phone: "0599002211",
    delegateName: "محمد علي",
    status: "delivered",
    paymentMethod: "cod",
    amount: 420,
    collectedAmount: 420,
    phoenixCommission: 50,
    merchantDue: 370,
    city: "رام الله",
    area: "الماصيون",
    createdAt: "2026-04-17T10:20:00",
    updatedAt: "2026-04-19T17:30:00",
  },
  {
    id: 7,
    orderNumber: "PX-1051",
    merchantName: "متجر الرياضة",
    customerName: "محمود صبح",
    phone: "0599881122",
    delegateName: "عبدالله سالم",
    status: "in_delivery",
    paymentMethod: "cod",
    amount: 275,
    collectedAmount: 0,
    phoenixCommission: 0,
    merchantDue: 0,
    city: "بيت لحم",
    area: "شارع الصف",
    createdAt: "2026-04-22T12:10:00",
    updatedAt: "2026-04-24T08:35:00",
  },
  {
    id: 8,
    orderNumber: "PX-1052",
    merchantName: "متجر الهدايا",
    customerName: "جود الحاج",
    phone: "0599445588",
    delegateName: "خالد أحمد",
    status: "delivered",
    paymentMethod: "cod",
    amount: 150,
    collectedAmount: 150,
    phoenixCommission: 18,
    merchantDue: 132,
    city: "نابلس",
    area: "المخفية",
    createdAt: "2026-04-16T14:45:00",
    updatedAt: "2026-04-18T15:10:00",
  },
  {
    id: 9,
    orderNumber: "PX-1038",
    merchantName: "متجر الإلكترونيات",
    customerName: "نور قدومي",
    phone: "0599117788",
    delegateName: "محمد علي",
    status: "returned",
    paymentMethod: "cod",
    amount: 560,
    collectedAmount: 0,
    phoenixCommission: 0,
    merchantDue: 0,
    city: "نابلس",
    area: "المخفية",
    createdAt: "2026-04-19T15:30:00",
    updatedAt: "2026-04-21T13:10:00",
  },
  {
    id: 10,
    orderNumber: "PX-1033",
    merchantName: "متجر الأزياء",
    customerName: "ديمة زواهرة",
    phone: "0599663355",
    delegateName: "عبدالله سالم",
    status: "returned",
    paymentMethod: "cod",
    amount: 220,
    collectedAmount: 0,
    phoenixCommission: 0,
    merchantDue: 0,
    city: "بيت لحم",
    area: "شارع الصف",
    createdAt: "2026-04-18T12:00:00",
    updatedAt: "2026-04-20T11:25:00",
  },
];

const RETURNED_ORDERS_DATA = [
  {
    id: 301,
    orderNumber: "PX-1047",
    merchantName: "متجر الكتب",
    customerName: "هبة جرار",
    delegateName: "خالد أحمد",
    returnReason: "تعذر الوصول إلى العميل بعد ثلاث محاولات مؤكدة.",
    city: "جنين",
    returnedAt: "2026-04-22T16:45:00",
  },
  {
    id: 302,
    orderNumber: "PX-1038",
    merchantName: "متجر الإلكترونيات",
    customerName: "نور قدومي",
    delegateName: "محمد علي",
    returnReason: "رفض العميل الاستلام بسبب اختلاف الصنف المطلوب.",
    city: "نابلس",
    returnedAt: "2026-04-21T13:10:00",
  },
  {
    id: 303,
    orderNumber: "PX-1033",
    merchantName: "متجر الأزياء",
    customerName: "ديمة زواهرة",
    delegateName: "عبدالله سالم",
    returnReason: "العنوان غير مكتمل ولم يتم تأكيد موقع التسليم.",
    city: "بيت لحم",
    returnedAt: "2026-04-20T11:25:00",
  },
];

export async function getAdminReports() {
  return REPORTS_DATA;
}

export async function getReturnedOrders() {
  return RETURNED_ORDERS_DATA;
}
